language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-sogou' ]; then cd .. && eval "mv $currentfolder generator-sogou" && cd generator-sogou; fi

